name: main-suite

on:
  pull_request:
    branches:
      - '*'
  push:
    branches:
      - main

jobs:
  validate:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    name: validate (20, ubuntu-latest)
    steps:
      - uses: actions/checkout@v4

      - name: Enable Corepack
        run: corepack enable

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          cache: yarn
          node-version: 20

      - name: Install dependencies
        run: yarn install

      - name: Check Prettier Formatting
        run: yarn prettier:check

      - name: Unit Testing
        run: yarn test:ci

      - name: Check coverage
        uses: codecov/codecov-action@v4
        with:
          verbose: true
          token: ${{ secrets.CODECOV_TOKEN }}
